# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e8dd2dbcd211a0ea466d9d9a2b51f9035e41cf88cc8517b6108dcbb62e3439b8e915ddd8568921ddac1a90c88b2793e3e9bf4529ddafc805b4c91b10c5baec

test:
  secret_key_base: 425357eed08c28d1a30cb875a2669a29ec4cbe545b7f2e3d0e41154732ed0994fb4a1c4eac3685c90d1a10a83c4fb1d5e056dafc79c01174187b64f9098a694a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
